name: Build to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

env:
  DOCKER_HUB_REGISTRY: crazyguys
  DOCKER_REPOSITORY: echo-server

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to Docker Hub
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_HUB_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG -t $DOCKER_HUB_REGISTRY/$DOCKER_REPOSITORY:latest .
          docker push $DOCKER_HUB_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
          docker push $DOCKER_HUB_REGISTRY/$DOCKER_REPOSITORY:latest
          echo "::set-output name=image::$DOCKER_HUB_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG"
